/**
 * GuanPlus.Identity.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface AddressModel {
    /**
     * 地址id
     */
    id?: string;

    /**
     * 实体id
     */
    sourceId?: string;

    /**
     * 地址类型
     */
    addressType?: string;

    /**
     * 街道
     */
    street?: string;

    /**
     * 区
     */
    area?: models.IdNameModel;

    /**
     * 市
     */
    city?: models.IdNameModel;

    /**
     * 省
     */
    province?: models.IdNameModel;

    /**
     * 邮编
     */
    postalCode?: string;

}
