/**
 * GuanPlus.Identity.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface CompanySubscriptionModel {
    /**
     * 订阅id
     */
    subscriptionNo?: number;

    /**
     * 公司id
     */
    companyId?: string;

    /**
     * 公司名称
     */
    companyName?: string;

    /**
     * 套餐名称
     */
    packageName?: string;

    /**
     * 开始日期
     */
    beginOn?: Date;

    /**
     * 到期日期
     */
    expireOn?: Date;

    /**
     * 还有...天过期
     */
    day?: number;

    /**
     * LogoSrc
     */
    logoSrc?: string;

    /**
     * 管理员
     */
    administrator?: models.UserModel;

}
