/**
 * GuanPlus.Identity.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface CompanyModel {
    /**
     * Id
     */
    id?: string;

    /**
     * TenantNo
     */
    tenantNo?: number;

    /**
     * 公司名称
     */
    companyName?: string;

    /**
     * 子区域
     */
    subdomain?: string;

    /**
     * 依法登记的名称
     */
    legalName?: string;

    /**
     * 地址
     */
    address?: models.AddressModel;

    /**
     * 邮政编码
     */
    postalCode?: string;

    /**
     * 
     */
    region?: string;

    /**
     * 
     */
    province?: string;

    /**
     * 
     */
    town?: string;

    /**
     * 行业
     */
    industry?: models.IdNameModel;

    /**
     * 
     */
    size?: string;

    /**
     * 性质
     */
    companyType?: CompanyModel.CompanyTypeEnum;

    /**
     * 
     */
    createdOn?: Date;

    /**
     * 
     */
    createdBy?: string;

    /**
     * LastUpdatedOn
     */
    lastUpdatedOn?: Date;

    /**
     * LastUpdatedBy
     */
    lastUpdatedBy?: string;

    /**
     * 状态
     */
    status?: CompanyModel.StatusEnum;

    /**
     * 到期日期
     */
    expireOn?: Date;

    /**
     * 是否过期
     */
    isExpired?: boolean;

    /**
     * 剩余天数
     */
    leftDays?: number;

    /**
     * 是否试用期
     */
    isTried?: boolean;

    /**
     * 是否是管理员
     */
    isAdmin?: boolean;

    /**
     * 版本Id
     */
    package?: models.PackageEnumModel;

    /**
     * 公司创建人的角色
     */
    roles?: Array<models.IdNameModel>;

    /**
     * 法人
     */
    legalPersonName?: string;

    /**
     * 注册资金
     */
    registeredCapital?: number;

    /**
     * 住所
     */
    inputAddress?: string;

    /**
     * 营业期限截至日期
     */
    businessEndDate?: Date;

    /**
     * 税号
     */
    taxNumber?: string;

}
export namespace CompanyModel {
    export enum CompanyTypeEnum {
        SmallScaleTaxpayers = <any> 'SmallScaleTaxpayers',
        GeneralTaxpayer = <any> 'GeneralTaxpayer',
        Other = <any> 'Other'
    }
    export enum StatusEnum {
        Creating = <any> 'Creating',
        Created = <any> 'Created',
        Provisioned = <any> 'Provisioned'
    }
}
