/**
 * GuanPlus.Identity.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface InvoiceModel {
    /**
     * 发票Id
     */
    invoiceId?: string;

    /**
     * 发票日期
     */
    invoiceOn?: Date;

    /**
     * 金额
     */
    amount?: number;

    /**
     * 发票抬头
     */
    title?: string;

    /**
     * 下载地址
     */
    url?: string;

    /**
     * 发票类型
     */
    invoiceTypeCode?: string;

    /**
     * 发票号
     */
    referenceNo?: string;

    /**
     * 发票状态
     */
    invoiceStatus?: string;

    /**
     * 申请开发票日期
     */
    requestedDate?: Date;

    /**
     * 申请人
     */
    requestedBy?: string;

    /**
     * 订单Id
     */
    orderIds?: Array<string>;

}
