/**
 * GuanPlus.Identity.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface OrderModel {
    /**
     * 订单ID
     */
    id?: string;

    /**
     * 订单号              商户订单号，适配每个渠道对此参数的要求，              必须在商户系统内唯一。(alipay: 1-64 位， wx: 2-32 位）
     */
    orderNo?: string;

    /**
     * 订单状态
     */
    orderStatus?: string;

    /**
     * 
     */
    companyId?: string;

    /**
     * 购买月数3，6，12
     */
    frequency?: number;

    /**
     * 每月价格
     */
    monthlyPrice?: number;

    /**
     * 支付金额              单位为对应币种的最小货币单位，              例如：人民币为分（如订单总金额为 1 元，此处请填 100）
     */
    nettAmount?: number;

    /**
     * 订单总金额（原价）
     */
    amount?: number;

    /**
     * 折扣
     */
    discount?: number;

    /**
     * 发票
     */
    invoice?: models.InvoiceModel;

    /**
     * 
     */
    packageId?: string;

    /**
     * 
     */
    packageName?: string;

    /**
     * 优惠码
     */
    couponCode?: string;

    /**
     * 优惠规则描述
     */
    couponDesc?: string;

    /**
     * 订单创建时间(charge对象返回时间)
     */
    createdOn?: Date;

    /**
     * 交易完后时间(返回支付结果时间)
     */
    transactionOn?: Date;

    /**
     * 支付渠道
     */
    channel?: models.ChannelModel;

    /**
     * 货币
     */
    currency?: models.CurrencyEnumModel;

    /**
     * 商品的描述信息，              该参数最长为 128 个 Unicode 字符，              yeepay_wap 对于该参数长度限制为 100 个 Unicode 字符。
     */
    body?: string;

    /**
     * IP地址               IPV4
     */
    clientIp?: string;

    /**
     * 创建人
     */
    createBy?: string;

    /**
     * Charge对象
     */
    charge?: models.Charge;

    /**
     * 联系人
     */
    orderContact?: models.OrderContactModel;

}
