/**
 * GuanPlus.Identity.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface UserModel {
    /**
     * Id
     */
    id?: string;

    /**
     * 手机号
     */
    phoneNumber?: string;

    /**
     * 手机号是否确认
     */
    phoneNumberComfirmed?: boolean;

    /**
     * 名称
     */
    name?: string;

    /**
     * Email
     */
    email?: string;

    /**
     * 邮箱是否确认
     */
    emailConfirmed?: boolean;

    /**
     * 密码
     */
    passwordHash?: string;

    /**
     * 
     */
    securityStamp?: string;

    /**
     * 
     */
    lockoutDate?: Date;

    /**
     * 
     */
    isSuperAdmin?: boolean;

    /**
     * 
     */
    lockoutEnable?: boolean;

    /**
     * 
     */
    status?: string;

    /**
     * 
     */
    accessFailedCount?: number;

    /**
     * 创建时间
     */
    createdDate?: Date;

    /**
     * 
     */
    createdBy?: string;

    /**
     * 注册来源
     */
    source?: models.RegisterSourceEnumModel;

    /**
     * 所属公司
     */
    companies?: Array<models.CompanyModel>;

    /**
     * 当前公司
     */
    currentCompany?: models.CompanyModel;

    /**
     * 是否激活
     */
    isActivated?: boolean;

    /**
     * 是否显示演示Demo窗口
     */
    isDisplayDemo?: string;

    /**
     * 是否为会计工厂
     */
    isAccountingFirm?: boolean;

}
