/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

/**
 * 账套
 */
export interface AccountBookSettingModel {
    /**
     * id
     */
    id?: string;

    /**
     * 所属账套
     */
    accountBook?: models.AccountBookModel;

    /**
     * 会计区间日期
     */
    accountPeriodDate?: Date;

    /**
     * 会计期间-年
     */
    accountPeriodYear?: number;

    /**
     * 当计期间-月
     */
    accountPeriodMonth?: number;

    /**
     * 开票金额
     */
    issueInvoiceAmount?: number;

    /**
     * 收票金额
     */
    receiveInvoiceAmount?: number;

    /**
     * 账套状态
     */
    status?: models.AccountBookSettingStatusEnumModel;

    /**
     * 备注
     */
    remark?: string;

    /**
     * 报税频率
     */
    taxReturnFrequency?: string;

}
