/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface AttachmentModel {
    /**
     * attachment Id
     */
    id?: string;

    /**
     * companyId
     */
    companyId?: string;

    /**
     * User Id
     */
    userId?: string;

    /**
     * 上传文件的路径
     */
    path?: string;

    /**
     * 上传文件的名称
     */
    fileName?: string;

    /**
     * 下载item 的url
     */
    url?: string;

    /**
     * 附件类型
     */
    attachmentType?: AttachmentModel.AttachmentTypeEnum;

    /**
     * 名称
     */
    originName?: string;

    /**
     * 实体类型
     */
    entityTypeCode?: string;

}
export namespace AttachmentModel {
    export enum AttachmentTypeEnum {
        None = <any> 'None',
        Bill = <any> 'Bill',
        Invoice = <any> 'Invoice',
        TravelItem = <any> 'TravelItem',
        Profile = <any> 'Profile',
        ReimbursementAudioMemo = <any> 'ReimbursementAudioMemo',
        PaymentRecord = <any> 'PaymentRecord',
        AccountVoucher = <any> 'AccountVoucher',
        Receipt = <any> 'Receipt',
        SalesOrder = <any> 'SalesOrder',
        ReceiveRecord = <any> 'ReceiveRecord',
        BankStatements = <any> 'BankStatements'
    }
}
