/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface AuxiliaryBusinessAccountingBalanceModel {
    /**
     * 联系人id
     */
    id?: string;

    /**
     * 期初余额
     */
    openingBalance?: number;

    /**
     * 辅助核算
     */
    auxiliaryBusinessAccountingType?: models.AuxiliaryBusinessAccountingTypeEnumModel;

    /**
     * 会计区间【年】(注：如果为空则是初始化科目)
     */
    accountPeriodYear?: number;

    /**
     * 会计区间【月】(注：如果为空则是初始化科目)
     */
    accountPeriodMonth?: number;

    /**
     * 联系人
     */
    contact?: models.IdNameModel;

    /**
     * 联系人类型
     */
    contactType?: string;

    /**
     * 交易类型
     */
    transactionType?: string;

    /**
     * 导入excel中对应的行数
     */
    importRow?: number;

    /**
     * ImportTaskId
     */
    importTaskId?: string;

}
