/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

/**
 * 银行对账单
 */
export interface BankStatementModel {
    /**
     * id
     */
    id?: string;

    /**
     * 交易日期
     */
    accountTransDate?: Date;

    /**
     * 票据编号
     */
    noteNumber?: string;

    /**
     * 币种？是否外键
     */
    currency?: string;

    /**
     * 对方账户名称
     */
    toAccountName?: string;

    /**
     * 对方账户号
     */
    toAccountNumber?: string;

    /**
     * 借方
     */
    debit?: number;

    /**
     * 贷方
     */
    credit?: number;

    /**
     * 余额
     */
    balance?: number;

    /**
     * 描述、摘要
     */
    description?: string;

    /**
     * 代理银行
     */
    agentBank?: string;

    /**
     * 操作员
     */
    operator?: string;

    /**
     * 位置
     */
    location?: string;

    /**
     * 对账状态
     */
    statementStatus?: models.StatementStatusEnumModel;

    /**
     * 银行账号
     */
    bankAccount?: models.IdNameModel;

    /**
     * 校验状态
     */
    status?: boolean;

    /**
     * 备注
     */
    remark?: string;

    /**
     * 创建时间
     */
    createdOn?: Date;

    /**
     * 创建人
     */
    createdBy?: string;

}
