/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface BuildingTaxItemModel {
    /**
     * 行次
     */
    num?: number;

    /**
     * 名字
     */
    name?: string;

    /**
     * 一般增值税
     */
    generalVAT?: number;

    /**
     * 免抵税额
     */
    expessVAT?: number;

    /**
     * 消费税
     */
    coumptionTax?: number;

    /**
     * 营业税
     */
    businessTax?: number;

    /**
     * 合计
     */
    sum?: number;

    /**
     * 税率
     */
    taxRate?: number;

    /**
     * 本期应纳税额
     */
    dutiableTax?: number;

    /**
     * 减免性质代码
     */
    reductionCode?: number;

    /**
     * 减免额
     */
    incomeRelief?: number;

    /**
     * 本期已缴税（费）额
     */
    paidTax?: number;

    /**
     * 本期应补（退）税（费）额
     */
    amountOfDuePaid?: number;

}
