/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface CurrentSalesItemModel {
    order?: number;

    /**
     * 税率
     */
    taxRate?: number;

    businessCategoryNames?: Array<string>;

    /**
     * 开具增值税专用发票
     */
    proInvoice?: models.SalesTaxModel;

    /**
     * 开局其他发票
     */
    otherInvoice?: models.SalesTaxModel;

    /**
     * 未开具发票
     */
    noInvoice?: models.SalesTaxModel;

    /**
     * 纳税检查调整
     */
    taxChange?: models.SalesTaxModel;

    /**
     * 合计
     */
    total?: models.SalesTaxModel;

    /**
     * 价税合计
     */
    allAccount?: number;

    actualAccount?: number;

    /**
     * 扣除后
     */
    deduction?: models.SalesTaxModel;

}
