/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

/**
 * 员工工资
 */
export interface EmployeePayrollModel {
    /**
     * 
     */
    id?: string;

    /**
     * 员工Id
     */
    employeeId?: string;

    /**
     * 编号
     */
    number?: string;

    /**
     * 身份证号
     */
    idNo?: string;

    /**
     * 姓名
     */
    name?: string;

    /**
     * 基本工资
     */
    baseSalary?: number;

    /**
     * 岗位工资
     */
    positionSalary?: number;

    /**
     * 奖金
     */
    bonus?: number;

    /**
     * 绩效
     */
    meritPay?: number;

    /**
     * 调整工资
     */
    adjustWages?: number;

    /**
     * 餐补
     */
    mealAllowance?: number;

    /**
     * 其他补助
     */
    otherAllowance?: number;

    /**
     * 交通补助
     */
    travelAllowance?: number;

    /**
     * 合计工资
     */
    totalSalary?: number;

    /**
     * 公司公积金
     */
    cProvidentFund?: number;

    /**
     * 个人公积金
     */
    pProvidentFund?: number;

    /**
     * 个人医疗保险
     */
    pEdicalCare?: number;

    /**
     * 个人养老保险
     */
    pPension?: number;

    /**
     * 个人失业保险
     */
    pUnemployment?: number;

    /**
     * 公司医疗保险
     */
    cEdicalCare?: number;

    /**
     * 公司养老保险
     */
    cPension?: number;

    /**
     * 公司失业保险
     */
    cUnemployment?: number;

    /**
     * 公司生育
     */
    cFertility?: number;

    /**
     * 公司工伤
     */
    cWorkInjury?: number;

    /**
     * 个人社保
     */
    pSocialSecurity?: number;

    /**
     * 公司社保
     */
    cSocialSecurity?: number;

    /**
     * 所得税
     */
    incomeTax?: number;

    /**
     * 实发工资
     */
    nettSalary?: number;

    /**
     * 人力成本
     */
    laborCost?: number;

    /**
     * 国籍 id为code name为名
     */
    national?: models.IdNameModel;

}
