/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

/**
 * 一般纳税人增值税表
 */
export interface GVATModel {
    /**
     * 年
     */
    year?: number;

    /**
     * 月
     */
    month?: number;

    /**
     * 详情
     */
    details?: Array<models.GVAItemModel>;

    /**
     * 纳税人姓名
     */
    taxpayerName?: string;

    /**
     * 纳税人识别id
     */
    taxpayerId?: string;

    /**
     * 行业
     */
    industryName?: string;

    /**
     * 法人
     */
    legalPersonName?: string;

    /**
     * 税款所属期--开始时间
     */
    startTime?: Date;

    /**
     * 税款所属期--截止时间
     */
    endTime?: Date;

}
