/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

/**
 * 凭证项Model
 */
export interface JournalEntryModel {
    /**
     * Id
     */
    id?: string;

    /**
     * 制单日期
     */
    accountedOn?: Date;

    /**
     * 凭证编号
     */
    journalEntryNumber?: string;

    /**
     * 描述
     */
    description?: string;

    /**
     * 附件张数
     */
    attachmentCount?: number;

    /**
     * 凭证类型
     */
    sourceType?: string;

    /**
     * 制单人
     */
    user?: models.IdNameModel;

    /**
     * 来源
     */
    source?: string;

    /**
     * 实体id
     */
    entityId?: string;

    /**
     * 实体编号
     */
    entityNumber?: string;

    /**
     * 实体模型编码
     */
    entityType?: JournalEntryModel.EntityTypeEnum;

    /**
     * 是否是结转凭证
     */
    isAccountPosting?: string;

    /**
     * 是否锁定
     */
    lock?: boolean;

    /**
     * 凭证类型
     */
    journalEntryType?: JournalEntryModel.JournalEntryTypeEnum;

    /**
     * 凭证子项
     */
    journalEntryLineItemModels?: Array<models.JournalEntryLineItemModel>;

    /**
     * 凭证附件
     */
    attachmentModels?: Array<models.AccountAttachmentModel>;

}
export namespace JournalEntryModel {
    export enum EntityTypeEnum {
        None = <any> 'None',
        Income = <any> 'Income',
        Outcome = <any> 'Outcome',
        Receivable = <any> 'Receivable',
        Payable = <any> 'Payable',
        Journal = <any> 'Journal',
        Banktransfer = <any> 'Banktransfer',
        Input = <any> 'Input',
        Output = <any> 'Output'
    }
    export enum JournalEntryTypeEnum {
        Init = <any> 'Init',
        Invoice = <any> 'Invoice',
        AccountTransaction = <any> 'AccountTransaction',
        FixedAsset = <any> 'FixedAsset',
        Payroll = <any> 'Payroll',
        Tax = <any> 'Tax',
        CarryForward = <any> 'CarryForward',
        InvoiceCertificationRollout = <any> 'InvoiceCertificationRollout',
        InvoiceCertification = <any> 'InvoiceCertification',
        InvoiceDeductingRollout = <any> 'InvoiceDeductingRollout'
    }
}
