/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

/**
 * 工资表
 */
export interface PayrollModel {
    /**
     * Id
     */
    id?: string;

    /**
     * 编码
     */
    number?: string;

    /**
     * 员工的工资
     */
    employeePayrolls?: Array<models.EmployeePayrollModel>;

    /**
     * 是否生成了工资表
     */
    status?: string;

    /**
     * 工资表的年
     */
    year?: number;

    /**
     * 工资表的月份
     */
    month?: number;

    /**
     * 工资记录id
     */
    wages?: number;

    /**
     * 公积金记录id
     */
    accumulationFund?: number;

    /**
     * 社保id
     */
    socialSecurity?: number;

    /**
     * 个税记录id
     */
    incomeTax?: number;

    /**
     * 是否锁定
     */
    lock?: boolean;

}
