/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Http, Headers, RequestOptionsArgs, Response, URLSearchParams,
  RequestMethod } from '@angular/http';
import { Injectable, Inject, Optional }  from '@angular/core';
import { Observable } from 'rxjs/Observable';
import * as models from '../model/models';
import { ACCOUNTING_BASE_PATH }                                         from '../variables';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class AccountTransLineItemApi {
    protected basePath = 'http://guanplus-api-accountingfirm-dev.cn-north-1.eb.amazonaws.com.cn';
    public defaultHeaders: Headers = new Headers();

    constructor(protected http: Http, @Optional()@Inject(ACCOUNTING_BASE_PATH) basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * 
     * 
     * @param bankaccountid 
     * @param accountTransactionType 
     * @param keyword 
     * @param startDate 
     * @param endDate 
     * @param tagidIds 
     * @param pageIndex 
     * @param pageSize 
     * @param carryForwardStatus 
     */
    public accountTransLineItemAccountContrastExport (bankaccountid?: string,
      accountTransactionType?: string,
      keyword?: string,
      startDate?: string,
      endDate?: string,
      tagidIds?: string,
      pageIndex?: string,
      pageSize?: string,
      carryForwardStatus?: string,
      extraHttpRequestParams?: any ): Observable<{}> {
        const path = this.basePath + '/api/v1/account_transaction_line_item/export';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (bankaccountid !== undefined) {
            queryParameters.set('bankaccountid', String(bankaccountid));
        }

        if (accountTransactionType !== undefined) {
            queryParameters.set('accountTransactionType', String(accountTransactionType));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startDate !== undefined) {
            queryParameters.set('startDate', String(startDate));
        }

        if (endDate !== undefined) {
            queryParameters.set('endDate', String(endDate));
        }

        if (tagidIds !== undefined) {
            queryParameters.set('tagidIds', String(tagidIds));
        }

        if (pageIndex !== undefined) {
            queryParameters.set('pageIndex', String(pageIndex));
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', String(pageSize));
        }

        if (carryForwardStatus !== undefined) {
            queryParameters.set('carryForwardStatus', String(carryForwardStatus));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 根据id 删除交易明细记录
     * 
     * @param accountTransId 
     * @param id 
     */
    public accountTransLineItemDelete (accountTransId: string,
      id: number,
      extraHttpRequestParams?: any ): Observable<any> {
        const path = this.basePath + '/api/v1/account_transaction_line_item/${accountTransId}/${id}'
            .replace('${' + 'accountTransId' + '}', String(accountTransId))
            .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'accountTransId' is not null or undefined
        if (accountTransId === null || accountTransId === undefined) {
            throw new Error('Required parameter accountTransId was null or undefined' +
              'when calling accountTransLineItemDelete.');
        }
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined' +
              'when calling accountTransLineItemDelete.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Delete,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 分页获取交易记录
     * 
     * @param bankaccountid 银行账户Id
     * @param accountTransactionType 交易类型：0、全部；1、收入；2、支出
     * @param keyword 关键字
     * @param startDate 开始时间
     * @param endDate 结束时间
     * @param tagIds 标签id,以逗号分隔
     * @param pageIndex 页数索引
     * @param pageSize 页数大小
     * @param carryForwardStatus 结转状态：0、全部或者空；1、未结转；2、已结转
     */
    public accountTransLineItemSearch (bankaccountid?: string,
      accountTransactionType?: string,
      keyword?: string,
      startDate?: string,
      endDate?: string,
      tagIds?: string,
      pageIndex?: string,
      pageSize?: string,
      carryForwardStatus?: string,
      extraHttpRequestParams?: any ): Observable<models.PagedResultAccountTransLineItemModel> {
        const path = this.basePath + '/api/v1/account_transaction_line_item/search';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (bankaccountid !== undefined) {
            queryParameters.set('bankaccountid', String(bankaccountid));
        }

        if (accountTransactionType !== undefined) {
            queryParameters.set('accountTransactionType', String(accountTransactionType));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startDate !== undefined) {
            queryParameters.set('startDate', String(startDate));
        }

        if (endDate !== undefined) {
            queryParameters.set('endDate', String(endDate));
        }

        if (tagIds !== undefined) {
            queryParameters.set('tagIds', String(tagIds));
        }

        if (pageIndex !== undefined) {
            queryParameters.set('pageIndex', String(pageIndex));
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', String(pageSize));
        }

        if (carryForwardStatus !== undefined) {
            queryParameters.set('carryForwardStatus', String(carryForwardStatus));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 获取收入或支持的总计
     * 返回的list数组中，第一个为收入总额，第二个为支出总额
     * @param bankaccountid 银行账户Id
     * @param accountTransactionType 交易类型：0、全部；1、收入；2、支出
     * @param keyword 关键字
     * @param startDate 开始时间
     * @param endDate 结束时间
     * @param tagIds 标签id,以逗号分隔
     * @param carryForwardStatus 结转状态：0、全部或者空；1、未结转；2、已结转
     */
    public accountTransLineItemTransactionSum (bankaccountid?: string,
      accountTransactionType?: string,
      keyword?: string,
      startDate?: string,
      endDate?: string,
      tagIds?: string,
      carryForwardStatus?: string,
      extraHttpRequestParams?: any ): Observable<Array<models.IdNameModel>> {
        const path = this.basePath + '/api/v1/account_transaction_line_item/sum';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (bankaccountid !== undefined) {
            queryParameters.set('bankaccountid', String(bankaccountid));
        }

        if (accountTransactionType !== undefined) {
            queryParameters.set('accountTransactionType', String(accountTransactionType));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startDate !== undefined) {
            queryParameters.set('startDate', String(startDate));
        }

        if (endDate !== undefined) {
            queryParameters.set('endDate', String(endDate));
        }

        if (tagIds !== undefined) {
            queryParameters.set('tagIds', String(tagIds));
        }

        if (carryForwardStatus !== undefined) {
            queryParameters.set('carryForwardStatus', String(carryForwardStatus));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
