/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Http, Headers, RequestOptionsArgs, Response, URLSearchParams,
  RequestMethod } from '@angular/http';
import { Injectable, Inject, Optional }  from '@angular/core';
import { Observable } from 'rxjs/Observable';
import * as models from '../model/models';
import { ACCOUNTING_BASE_PATH }                                         from '../variables';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class BankTransferApi {
    protected basePath = 'http://guanplus-api-accountingfirm-dev.cn-north-1.eb.amazonaws.com.cn';
    public defaultHeaders: Headers = new Headers();

    constructor(protected http: Http, @Optional()@Inject(ACCOUNTING_BASE_PATH) basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * 获取银行互转
     * 
     * @param id 
     */
    public bankTransferGet (id: string,
      extraHttpRequestParams?: any ): Observable<models.BankTransferModel> {
        const path = this.basePath + '/api/v1/bank_transfer/${Id}'
            .replace('${' + 'Id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined' +
              'when calling bankTransferGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 新增银行互转
     * 
     * @param bankTransferModel 
     */
    public bankTransferPost (bankTransferModel: models.BankTransferModel,
      extraHttpRequestParams?: any ): Observable<models.BankTransferModel> {
        const path = this.basePath + '/api/v1/bank_transfer';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'bankTransferModel' is not null or undefined
        if (bankTransferModel === null || bankTransferModel === undefined) {
            throw new Error('Required parameter bankTransferModel was null or undefined' +
              'when calling bankTransferPost.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(bankTransferModel);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 银行对账单同步交易记录
     * 
     * @param bankStatementSynchronizeModels 
     */
    public bankTransferSynchronize (bankStatementSynchronizeModels: Array<models.BankStatementTransferSynchronizeModel>,
      extraHttpRequestParams?: any ): Observable<Array<models.BankStatementTransferSynchronizeModel>> {
        const path = this.basePath + '/api/v1/bank_transfer/synchronize';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'bankStatementSynchronizeModels' is not null or undefined
        if (bankStatementSynchronizeModels === null || bankStatementSynchronizeModels === undefined) {
            throw new Error('Required parameter bankStatementSynchronizeModels was null or undefined' +
              'when calling bankTransferSynchronize.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(bankStatementSynchronizeModels);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 编辑银行互转
     * 
     * @param bankTransferModel 
     */
    public bankTransferUpdate (bankTransferModel: models.BankTransferModel,
      extraHttpRequestParams?: any ): Observable<models.BankTransferModel> {
        const path = this.basePath + '/api/v1/bank_transfer';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'bankTransferModel' is not null or undefined
        if (bankTransferModel === null || bankTransferModel === undefined) {
            throw new Error('Required parameter bankTransferModel was null or undefined' +
              'when calling bankTransferUpdate.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Put,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(bankTransferModel);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
