/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Http, Headers, RequestOptionsArgs, Response, URLSearchParams,
  RequestMethod } from '@angular/http';
import { Injectable, Inject, Optional }  from '@angular/core';
import { Observable } from 'rxjs/Observable';
import * as models from '../model/models';
import { ACCOUNTING_BASE_PATH }                                         from '../variables';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class BankAccountApi {
    protected basePath = 'http://guanplus-api-accountingfirm-dev.cn-north-1.eb.amazonaws.com.cn';
    public defaultHeaders: Headers = new Headers();

    constructor(protected http: Http, @Optional()@Inject(ACCOUNTING_BASE_PATH) basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * 批量保存
     * 
     * @param bankAccountModels 
     */
    public bankAccountBatchUpdate (bankAccountModels: Array<models.BankAccountModel>,
      extraHttpRequestParams?: any ): Observable<models.BoolResultModel> {
        const path = this.basePath + '/api/v1/bank_account/batch';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'bankAccountModels' is not null or undefined
        if (bankAccountModels === null || bankAccountModels === undefined) {
            throw new Error('Required parameter bankAccountModels was null or undefined' +
              'when calling bankAccountBatchUpdate.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(bankAccountModels);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 根据id 删除银行账户
     * 
     * @param id 
     */
    public bankAccountDelete (id: string,
      extraHttpRequestParams?: any ): Observable<any> {
        const path = this.basePath + '/api/v1/bank_account/${id}'
            .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined' +
              'when calling bankAccountDelete.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Delete,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 导出上传的错误数据
     * 
     * @param attachmentId 附件id
     */
    public bankAccountExportError (attachmentId: string,
      extraHttpRequestParams?: any ): Observable<{}> {
        const path = this.basePath + '/api/v1/bank_account/${attachmentId}/export_error'
            .replace('${' + 'attachmentId' + '}', String(attachmentId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'attachmentId' is not null or undefined
        if (attachmentId === null || attachmentId === undefined) {
            throw new Error('Required parameter attachmentId was null or undefined' +
              'when calling bankAccountExportError.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 获取所有银行账户
     * 
     * @param accountId 
     */
    public bankAccountGet (accountId?: string,
      extraHttpRequestParams?: any ): Observable<Array<models.BankAccountModel>> {
        const path = this.basePath + '/api/v1/bank_account/assign';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (accountId !== undefined) {
            queryParameters.set('accountId', String(accountId));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 获取所有银行账户
     * 
     */
    public bankAccountGetAll (extraHttpRequestParams?: any ): Observable<Array<models.BankAccountModel>> {
        const path = this.basePath + '/api/v1/bank_account/all';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 分页获取银行账户
     * 
     * @param bankAccountTypeId 
     * @param pageIndex 页数索引
     * @param pageSize 页数大小
     */
    public bankAccountGet_1 (bankAccountTypeId?: string,
      pageIndex?: string,
      pageSize?: string,
      extraHttpRequestParams?: any ): Observable<models.PagedResultBankAccountModel> {
        const path = this.basePath + '/api/v1/bank_account/search';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (bankAccountTypeId !== undefined) {
            queryParameters.set('bankAccountTypeId', String(bankAccountTypeId));
        }

        if (pageIndex !== undefined) {
            queryParameters.set('pageIndex', String(pageIndex));
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', String(pageSize));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 根据id获取银行账户
     * 
     * @param id 
     */
    public bankAccountGet_2 (id: string,
      extraHttpRequestParams?: any ): Observable<models.BankAccountModel> {
        const path = this.basePath + '/api/v1/bank_account/${id}'
            .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined' +
              'when calling bankAccountGet_2.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 导入
     * 
     * @param year 年
     * @param month 月
     */
    public bankAccountImport (year: number,
      month: number,
      extraHttpRequestParams?: any ): Observable<models.AttachmentModel> {
        const path = this.basePath + '/api/v1/bank_account/${year}/${month}/import'
            .replace('${' + 'year' + '}', String(year))
            .replace('${' + 'month' + '}', String(month));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'year' is not null or undefined
        if (year === null || year === undefined) {
            throw new Error('Required parameter year was null or undefined' +
              'when calling bankAccountImport.');
        }
        // verify required parameter 'month' is not null or undefined
        if (month === null || month === undefined) {
            throw new Error('Required parameter month was null or undefined' +
              'when calling bankAccountImport.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 新增银行账户
     * 
     * @param bankAccountModel 
     */
    public bankAccountPost (bankAccountModel: models.BankAccountModel,
      extraHttpRequestParams?: any ): Observable<models.BankAccountModel> {
        const path = this.basePath + '/api/v1/bank_account';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'bankAccountModel' is not null or undefined
        if (bankAccountModel === null || bankAccountModel === undefined) {
            throw new Error('Required parameter bankAccountModel was null or undefined' +
              'when calling bankAccountPost.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(bankAccountModel);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 修改银行账户
     * 
     * @param bankAccountModel 
     */
    public bankAccountPut (bankAccountModel: models.BankAccountModel,
      extraHttpRequestParams?: any ): Observable<models.BankAccountModel> {
        const path = this.basePath + '/api/v1/bank_account';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'bankAccountModel' is not null or undefined
        if (bankAccountModel === null || bankAccountModel === undefined) {
            throw new Error('Required parameter bankAccountModel was null or undefined' +
              'when calling bankAccountPut.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Put,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(bankAccountModel);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     */
    public bankAccountTestCache (extraHttpRequestParams?: any ): Observable<{}> {
        const path = this.basePath + '/api/v1/bank_account/constr';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
