/**
 * GuanPlus.AccountingFirm.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Http, Headers, RequestOptionsArgs, Response, URLSearchParams,
  RequestMethod } from '@angular/http';
import { Injectable, Inject, Optional }  from '@angular/core';
import { Observable } from 'rxjs/Observable';
import * as models from '../model/models';
import { ACCOUNTING_BASE_PATH }                                         from '../variables';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class InvoiceApi {
    protected basePath = 'http://guanplus-api-accountingfirm-dev.cn-north-1.eb.amazonaws.com.cn';
    public defaultHeaders: Headers = new Headers();

    constructor(protected http: Http, @Optional()@Inject(ACCOUNTING_BASE_PATH) basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * 批量删除
     * 
     * @param importTaskId 
     */
    public invoiceBatchDelete (importTaskId: string,
      extraHttpRequestParams?: any ): Observable<any> {
        const path = this.basePath + '/api/v1/invoice/${importTaskId}/batchdel'
            .replace('${' + 'importTaskId' + '}', String(importTaskId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'importTaskId' is not null or undefined
        if (importTaskId === null || importTaskId === undefined) {
            throw new Error('Required parameter importTaskId was null or undefined' +
              'when calling invoiceBatchDelete.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Delete,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param model 
     */
    public invoiceDeduct (model: models.InvoiceDeductModel,
      extraHttpRequestParams?: any ): Observable<models.BoolResultModel> {
        const path = this.basePath + '/api/v1/invoice/deduct';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'model' is not null or undefined
        if (model === null || model === undefined) {
            throw new Error('Required parameter model was null or undefined' +
              'when calling invoiceDeduct.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(model);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param invoiceDeductStatus 
     * @param keyword 
     * @param startDate 
     * @param endDate 
     * @param invoiceNumber 
     * @param pageIndex 
     * @param pageSize 
     */
    public invoiceDeductExport (invoiceDeductStatus?: string,
      keyword?: string,
      startDate?: string,
      endDate?: string,
      invoiceNumber?: string,
      pageIndex?: string,
      pageSize?: string,
      extraHttpRequestParams?: any ): Observable<string> {
        const path = this.basePath + '/api/v1/invoice/deduct_export';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (invoiceDeductStatus !== undefined) {
            queryParameters.set('invoiceDeductStatus', String(invoiceDeductStatus));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startDate !== undefined) {
            queryParameters.set('startDate', String(startDate));
        }

        if (endDate !== undefined) {
            queryParameters.set('endDate', String(endDate));
        }

        if (invoiceNumber !== undefined) {
            queryParameters.set('invoiceNumber', String(invoiceNumber));
        }

        if (pageIndex !== undefined) {
            queryParameters.set('pageIndex', String(pageIndex));
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', String(pageSize));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 抵扣的3中状态的查找
     * 
     * @param invoiceDeductStatus 
     * @param keyword 
     * @param startDate 
     * @param endDate 
     * @param invoiceNumber 
     * @param pageIndex 
     * @param pageSize 
     */
    public invoiceDeductSearch (invoiceDeductStatus?: string,
      keyword?: string,
      startDate?: string,
      endDate?: string,
      invoiceNumber?: string,
      pageIndex?: string,
      pageSize?: string,
      extraHttpRequestParams?: any ): Observable<models.InvoiceModel> {
        const path = this.basePath + '/api/v1/invoice/deduct_search';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (invoiceDeductStatus !== undefined) {
            queryParameters.set('invoiceDeductStatus', String(invoiceDeductStatus));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startDate !== undefined) {
            queryParameters.set('startDate', String(startDate));
        }

        if (endDate !== undefined) {
            queryParameters.set('endDate', String(endDate));
        }

        if (invoiceNumber !== undefined) {
            queryParameters.set('invoiceNumber', String(invoiceNumber));
        }

        if (pageIndex !== undefined) {
            queryParameters.set('pageIndex', String(pageIndex));
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', String(pageSize));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param id 
     */
    public invoiceDelete (id: string,
      extraHttpRequestParams?: any ): Observable<any> {
        const path = this.basePath + '/api/v1/invoice/${id}'
            .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined' +
              'when calling invoiceDelete.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Delete,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param id 
     */
    public invoiceGet (id: string,
      extraHttpRequestParams?: any ): Observable<models.InvoiceModel> {
        const path = this.basePath + '/api/v1/invoice/${id}'
            .replace('${' + 'id' + '}', String(id));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined' +
              'when calling invoiceGet.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 根据ImportTaskId获取导入认证清单的未找到发票号或者税额为匹配的数量
     * 
     * @param importTaskId 
     */
    public invoiceImportCertificationHistory (importTaskId: string,
      extraHttpRequestParams?: any ): Observable<models.ImportCertificationResultModel> {
        const path = this.basePath + '/api/v1/invoice/import_certification/${importTaskId}'
            .replace('${' + 'importTaskId' + '}', String(importTaskId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'importTaskId' is not null or undefined
        if (importTaskId === null || importTaskId === undefined) {
            throw new Error('Required parameter importTaskId was null or undefined' +
              'when calling invoiceImportCertificationHistory.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 根据ImportTaskId获取开票信息
     * 
     * @param importTaskId 
     */
    public invoiceImportHistory (importTaskId: string,
      extraHttpRequestParams?: any ): Observable<Array<models.InvoiceModel>> {
        const path = this.basePath + '/api/v1/invoice/import_history/${importTaskId}'
            .replace('${' + 'importTaskId' + '}', String(importTaskId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'importTaskId' is not null or undefined
        if (importTaskId === null || importTaskId === undefined) {
            throw new Error('Required parameter importTaskId was null or undefined' +
              'when calling invoiceImportHistory.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param invoiceModel 
     */
    public invoicePost (invoiceModel: models.InvoiceModel,
      extraHttpRequestParams?: any ): Observable<models.InvoiceModel> {
        const path = this.basePath + '/api/v1/invoice';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'invoiceModel' is not null or undefined
        if (invoiceModel === null || invoiceModel === undefined) {
            throw new Error('Required parameter invoiceModel was null or undefined' +
              'when calling invoicePost.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(invoiceModel);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param invoiceModel 
     */
    public invoicePut (invoiceModel: models.InvoiceModel,
      extraHttpRequestParams?: any ): Observable<models.InvoiceModel> {
        const path = this.basePath + '/api/v1/invoice';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'invoiceModel' is not null or undefined
        if (invoiceModel === null || invoiceModel === undefined) {
            throw new Error('Required parameter invoiceModel was null or undefined' +
              'when calling invoicePut.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Put,
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(invoiceModel);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 
     * 
     * @param entityType 
     * @param invoiceType 
     * @param invoiceStatus 
     * @param invoiceDeductStatus 
     * @param keyword 
     * @param startDate 
     * @param endDate 
     * @param pageIndex 
     * @param pageSize 
     */
    public invoiceSearch (entityType?: string,
      invoiceType?: string,
      invoiceStatus?: string,
      invoiceDeductStatus?: string,
      keyword?: string,
      startDate?: string,
      endDate?: string,
      pageIndex?: string,
      pageSize?: string,
      extraHttpRequestParams?: any ): Observable<models.InvoiceModel> {
        const path = this.basePath + '/api/v1/invoice/search';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (entityType !== undefined) {
            queryParameters.set('entityType', String(entityType));
        }

        if (invoiceType !== undefined) {
            queryParameters.set('invoiceType', String(invoiceType));
        }

        if (invoiceStatus !== undefined) {
            queryParameters.set('invoiceStatus', String(invoiceStatus));
        }

        if (invoiceDeductStatus !== undefined) {
            queryParameters.set('invoiceDeductStatus', String(invoiceDeductStatus));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startDate !== undefined) {
            queryParameters.set('startDate', String(startDate));
        }

        if (endDate !== undefined) {
            queryParameters.set('endDate', String(endDate));
        }

        if (pageIndex !== undefined) {
            queryParameters.set('pageIndex', String(pageIndex));
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', String(pageSize));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 抵扣的统计
     * 
     * @param invoiceDeductStatus 
     * @param keyword 
     * @param startDate 
     * @param endDate 
     * @param invoiceNumber 
     * @param pageIndex 
     * @param pageSize 
     */
    public invoiceStatistics (invoiceDeductStatus?: string,
      keyword?: string,
      startDate?: string,
      endDate?: string,
      invoiceNumber?: string,
      pageIndex?: string,
      pageSize?: string,
      extraHttpRequestParams?: any ): Observable<models.DeductStatisticModels> {
        const path = this.basePath + '/api/v1/invoice/statistics';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (invoiceDeductStatus !== undefined) {
            queryParameters.set('invoiceDeductStatus', String(invoiceDeductStatus));
        }

        if (keyword !== undefined) {
            queryParameters.set('keyword', String(keyword));
        }

        if (startDate !== undefined) {
            queryParameters.set('startDate', String(startDate));
        }

        if (endDate !== undefined) {
            queryParameters.set('endDate', String(endDate));
        }

        if (invoiceNumber !== undefined) {
            queryParameters.set('invoiceNumber', String(invoiceNumber));
        }

        if (pageIndex !== undefined) {
            queryParameters.set('pageIndex', String(pageIndex));
        }

        if (pageSize !== undefined) {
            queryParameters.set('pageSize', String(pageSize));
        }

        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Get,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * 上传附件
     * 
     * @param invoiceId 
     */
    public invoiceUpload (invoiceId: string,
      extraHttpRequestParams?: any ): Observable<Array<models.AccountAttachmentModel>> {
        const path = this.basePath + '/api/v1/invoice/upload/${invoiceId}'
            .replace('${' + 'invoiceId' + '}', String(invoiceId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'invoiceId' is not null or undefined
        if (invoiceId === null || invoiceId === undefined) {
            throw new Error('Required parameter invoiceId was null or undefined' +
              'when calling invoiceUpload.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: RequestMethod.Post,
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
